export const data = [
  { city: "Algiers", country: "Algeria", continent: "Africa" },
  { city: "Luanda", country: "Angola", continent: "Africa" },
  { city: "Porto-Novo", country: "Benin", continent: "Africa" },
  { city: "Gaborone", country: "Botswana", continent: "Africa" },
  { city: "Ouagadougou", country: "Burkina Faso", continent: "Africa" },
  { city: "Gitega", country: "Burundi", continent: "Africa" },
  { city: "Praia", country: "Cabo Verde", continent: "Africa" },
  { city: "Yaoundé", country: "Cameroon", continent: "Africa" },
  { city: "Bangui", country: "Central African Republic", continent: "Africa" },
  { city: "N'Djamena", country: "Chad", continent: "Africa" },
  { city: "Moroni", country: "Comoros", continent: "Africa" },
  {
    city: "Kinshasa",
    country: "Democratic Republic of Congo",
    continent: "Africa",
  },
  {
    city: "Brazzaville",
    country: "Congo",
    continent: "Africa",
  },
  { city: "Yamoussoukro", country: "Côte d'Ivoire", continent: "Africa" },
  { city: "Djibouti City", country: "Djibouti", continent: "Africa" },
  { city: "Cairo", country: "Egypt", continent: "Africa" },
  { city: "Malabo", country: "Equatorial Guinea", continent: "Africa" },
  { city: "Asmara", country: "Eritrea", continent: "Africa" },
  { city: "Mbabana", country: "Eswatini", continent: "Africa" },
  { city: "Addis Ababa", country: "Ethiopia", continent: "Africa" },
  { city: "Libreville", country: "Gabon", continent: "Africa" },
  { city: "Banjul", country: "Gambia", continent: "Africa" },
  { city: "Accra", country: "Ghana", continent: "Africa" },
  { city: "Conakry", country: "Guinea", continent: "Africa" },
  // { city: "Bissau", country: "Guinea-Bissau", continent: "Africa" },
  { city: "Nairobi", country: "Kenya", continent: "Africa" },
  { city: "Maseru", country: "Lesotho", continent: "Africa" },
  { city: "Monrovia", country: "Liberia", continent: "Africa" },
  { city: "Tripoli", country: "Libya", continent: "Africa" },
  { city: "Antananarivo", country: "Madagascar", continent: "Africa" },
  { city: "Lilongwe", country: "Malawi", continent: "Africa" },
  { city: "Bamako", country: "Mali", continent: "Africa" },
  { city: "Nouakchott", country: "Mauritania", continent: "Africa" },
  { city: "Port Louis", country: "Mauritius", continent: "Africa" },
  { city: "Rabat", country: "Morocco", continent: "Africa" },
  { city: "Maputo", country: "Mozambique", continent: "Africa" },
  { city: "Windhoek", country: "Namibia", continent: "Africa" },
  { city: "Niamey", country: "Niger", continent: "Africa" },
  { city: "Abuja", country: "Nigeria", continent: "Africa" },
  { city: "Kigali", country: "Rwanda", continent: "Africa" },
  // { city: "São Tomé", country: "São Tomé and Príncipe", continent: "Africa" },
  { city: "Dakar", country: "Senegal", continent: "Africa" },
  { city: "Victoria", country: "Seychelles", continent: "Africa" },
  { city: "Freetown", country: "Sierra Leone", continent: "Africa" },
  { city: "Mogadishu", country: "Somalia", continent: "Africa" },
  {
    city: "Pretoria, Bloemfontein, Cape Town",
    country: "South Africa",
    continent: "Africa",
  },
  { city: "Juba", country: "South Sudan", continent: "Africa" },
  { city: "Khartoum", country: "Sudan", continent: "Africa" },
  { city: "Dodoma", country: "Tanzania", continent: "Africa" },
  { city: "Lomé", country: "Togo", continent: "Africa" },
  { city: "Tunis", country: "Tunisia", continent: "Africa" },
  { city: "Kampala", country: "Uganda", continent: "Africa" },
  { city: "Laayoune", country: "Western Sahara", continent: "Africa" },

  { city: "Buenos Aires", country: "Argentina", continent: "South America" },
  { city: "Santiago", country: "Chile", continent: "South America" },
  { city: "Lima", country: "Peru", continent: "South America" },
  { city: "Brasília", country: "Brazil", continent: "South America" },
  { city: "Montevideo", country: "Uruguay", continent: "South America" },
  { city: "Asunción", country: "Paraguay", continent: "South America" },
  { city: "Quito", country: "Ecuador", continent: "South America" },
  { city: "La Paz", country: "Bolivia", continent: "South America" },
  { city: "Bogotá", country: "Colombia", continent: "South America" },
  { city: "Caracas", country: "Venezuela", continent: "South America" },
  { city: "Georgetown", country: "Guyana", continent: "South America" },
  { city: "Paramaribo", country: "Suriname", continent: "South America" },
  { city: "Cayenne", country: "French Guiana", continent: "South America" },

  { city: "Tirana", country: "Albania", continent: "Europe" },
  // { city: "Andorra la Vella", country: "Andorra", continent: "Europe" },
  { city: "Vienna", country: "Austria", continent: "Europe" },
  { city: "Baku", country: "Azerbaijan", continent: "Europe" },
  { city: "Minsk", country: "Belarus", continent: "Europe" },
  { city: "Brussels", country: "Belgium", continent: "Europe" },
  { city: "Sarajevo", country: "Bosnia and Herzegovina", continent: "Europe" },
  { city: "Sofia", country: "Bulgaria", continent: "Europe" },
  { city: "Zagreb", country: "Croatia", continent: "Europe" },
  { city: "Nicosia", country: "Cyprus", continent: "Europe" },
  { city: "Prague", country: "Czech Republic", continent: "Europe" },
  { city: "Copenhagen", country: "Denmark", continent: "Europe" },
  { city: "Tallinn", country: "Estonia", continent: "Europe" },
  { city: "Helsinki", country: "Finland", continent: "Europe" },
  { city: "Paris", country: "France", continent: "Europe" },
  { city: "Tbilisi", country: "Georgia", continent: "Europe" },
  { city: "Berlin", country: "Germany", continent: "Europe" },
  { city: "Athens", country: "Greece", continent: "Europe" },
  { city: "Budapest", country: "Hungary", continent: "Europe" },
  { city: "Reykjavík", country: "Iceland", continent: "Europe" },
  { city: "Dublin", country: "Ireland", continent: "Europe" },
  { city: "Rome", country: "Italy", continent: "Europe" },
  { city: "Pristina", country: "Kosovo", continent: "Europe" },
  { city: "Riga", country: "Latvia", continent: "Europe" },
  { city: "Vaduz", country: "Liechtenstein", continent: "Europe" },
  { city: "Vilnius", country: "Lithuania", continent: "Europe" },
  // { city: "Luxembourg", country: "Luxembourg", continent: "Europe" },
  { city: "Skopje", country: "North Macedonia", continent: "Europe" },
  { city: "Valletta", country: "Malta", continent: "Europe" },
  { city: "Chișinău", country: "Moldova", continent: "Europe" },
  // { city: "Monaco", country: "Monaco", continent: "Europe" },
  { city: "Podgorica", country: "Montenegro", continent: "Europe" },
  { city: "Amsterdam", country: "Netherlands", continent: "Europe" },
  { city: "Oslo", country: "Norway", continent: "Europe" },
  { city: "Warsaw", country: "Poland", continent: "Europe" },
  { city: "Lisbon", country: "Portugal", continent: "Europe" },
  { city: "Bucharest", country: "Romania", continent: "Europe" },
  { city: "Moscow", country: "Russia", continent: "Europe" },
  // { city: "San Marino", country: "San Marino", continent: "Europe" },
  { city: "Belgrade", country: "Serbia", continent: "Europe" },
  { city: "Bratislava", country: "Slovakia", continent: "Europe" },
  { city: "Ljubljana", country: "Slovenia", continent: "Europe" },
  { city: "Madrid", country: "Spain", continent: "Europe" },
  { city: "Stockholm", country: "Sweden", continent: "Europe" },
  { city: "Bern", country: "Switzerland", continent: "Europe" },
  { city: "Kyiv", country: "Ukraine", continent: "Europe" },
  { city: "London", country: "United Kingdom", continent: "Europe" },
  // { city: "Vatican City", country: "Vatican City", continent: "Europe" },

  { city: "Kabul", country: "Afghanistan", continent: "Asia" },
  { city: "Baku", country: "Azerbaijan", continent: "Asia" },
  { city: "Dhaka", country: "Bangladesh", continent: "Asia" },
  { city: "Thimphu", country: "Bhutan", continent: "Asia" },
  { city: "Naypyidaw", country: "Myanmar", continent: "Asia" },
  { city: "Phnom Penh", country: "Cambodia", continent: "Asia" },
  { city: "Beijing", country: "China", continent: "Asia" },
  { city: "Dili", country: "East Timor", continent: "Asia" },
  { city: "Tbilisi", country: "Georgia", continent: "Asia" },
  { city: "New Delhi", country: "India", continent: "Asia" },
  { city: "Jakarta", country: "Indonesia", continent: "Asia" },
  { city: "Tehran", country: "Iran", continent: "Asia" },
  { city: "Baghdad", country: "Iraq", continent: "Asia" },
  { city: "Jerusalem", country: "Israel", continent: "Asia" },
  { city: "Tokyo", country: "Japan", continent: "Asia" },
  { city: "Amman", country: "Jordan", continent: "Asia" },
  { city: "Nur-Sultan", country: "Kazakhstan", continent: "Asia" },
  { city: "Pyongyang", country: "North Korea", continent: "Asia" },
  { city: "Seoul", country: "South Korea", continent: "Asia" },
  { city: "Vientiane", country: "Laos", continent: "Asia" },
  { city: "Beirut", country: "Lebanon", continent: "Asia" },
  { city: "Kuala Lumpur", country: "Malaysia", continent: "Asia" },
  { city: "Malé", country: "Maldives", continent: "Asia" },
  { city: "Ulaanbaatar", country: "Mongolia", continent: "Asia" },
  { city: "Kathmandu", country: "Nepal", continent: "Asia" },
  { city: "Islamabad", country: "Pakistan", continent: "Asia" },
  { city: "Manila", country: "Philippines", continent: "Asia" },
  { city: "Doha", country: "Qatar", continent: "Asia" },
  { city: "Riyadh", country: "Saudi Arabia", continent: "Asia" },
  // { city: "Singapore", country: "Singapore", continent: "Asia" },
  { city: "Colombo", country: "Sri Lanka", continent: "Asia" },
  { city: "Damascus", country: "Syria", continent: "Asia" },
  { city: "Dushanbe", country: "Tajikistan", continent: "Asia" },
  { city: "Bangkok", country: "Thailand", continent: "Asia" },
  { city: "Ankara", country: "Turkey", continent: "Asia" },
  { city: "Ashgabat", country: "Turkmenistan", continent: "Asia" },
  { city: "Hanoi", country: "Vietnam", continent: "Asia" },
  { city: "Sana'a", country: "Yemen", continent: "Asia" },
];
