export const data = [
  { city: "Algiers", country: "Algeria", continent: "Africa" },
  { city: "Luanda", country: "Angola", continent: "Africa" },
  { city: "Porto-Novo", country: "Benin", continent: "Africa" },
  { city: "Gaborone", country: "Botswana", continent: "Africa" },
  { city: "Ouagadougou", country: "Burkina Faso", continent: "Africa" },
  { city: "Gitega", country: "Burundi", continent: "Africa" },
  { city: "Praia", country: "Cabo Verde", continent: "Africa" },
  { city: "Yaoundé", country: "Cameroon", continent: "Africa" },
  { city: "Bangui", country: "Central African Republic", continent: "Africa" },
  { city: "N'Djamena", country: "Chad", continent: "Africa" },
  { city: "Moroni", country: "Comoros", continent: "Africa" },
  {
    city: "Kinshasa",
    country: "Democratic Republic of Congo, ",
    continent: "Africa",
  },
  {
    city: "Brazzaville",
    country: "Congo",
    continent: "Africa",
  },
  { city: "Yamoussoukro", country: "Côte d'Ivoire", continent: "Africa" },
  { city: "Djibouti City", country: "Djibouti", continent: "Africa" },
  { city: "Cairo", country: "Egypt", continent: "Africa" },
  { city: "Malabo", country: "Equatorial Guinea", continent: "Africa" },
  { city: "Asmara", country: "Eritrea", continent: "Africa" },
  { city: "Mbabana", country: "Eswatini", continent: "Africa" },
  { city: "Addis Ababa", country: "Ethiopia", continent: "Africa" },
  { city: "Libreville", country: "Gabon", continent: "Africa" },
  { city: "Banjul", country: "Gambia", continent: "Africa" },
  { city: "Accra", country: "Ghana", continent: "Africa" },
  { city: "Conakry", country: "Guinea", continent: "Africa" },
  { city: "Bissau", country: "Guinea-Bissau", continent: "Africa" },
  { city: "Nairobi", country: "Kenya", continent: "Africa" },
  { city: "Maseru", country: "Lesotho", continent: "Africa" },
  { city: "Monrovia", country: "Liberia", continent: "Africa" },
  { city: "Tripoli", country: "Libya", continent: "Africa" },
  { city: "Antananarivo", country: "Madagascar", continent: "Africa" },
  { city: "Lilongwe", country: "Malawi", continent: "Africa" },
  { city: "Bamako", country: "Mali", continent: "Africa" },
  { city: "Nouakchott", country: "Mauritania", continent: "Africa" },
  { city: "Port Louis", country: "Mauritius", continent: "Africa" },
  { city: "Rabat", country: "Morocco", continent: "Africa" },
  { city: "Maputo", country: "Mozambique", continent: "Africa" },
  { city: "Windhoek", country: "Namibia", continent: "Africa" },
  { city: "Niamey", country: "Niger", continent: "Africa" },
  { city: "Abuja", country: "Nigeria", continent: "Africa" },
  { city: "Kigali", country: "Rwanda", continent: "Africa" },
  { city: "São Tomé", country: "São Tomé and Príncipe", continent: "Africa" },
  { city: "Dakar", country: "Senegal", continent: "Africa" },
  { city: "Victoria", country: "Seychelles", continent: "Africa" },
  { city: "Freetown", country: "Sierra Leone", continent: "Africa" },
  { city: "Mogadishu", country: "Somalia", continent: "Africa" },
  {
    city: "Pretoria, Bloemfontein, Cape Town",
    country: "South Africa",
    continent: "Africa",
  },
  { city: "Juba", country: "South Sudan", continent: "Africa" },
  { city: "Khartoum", country: "Sudan", continent: "Africa" },
  { city: "Mbabana", country: "Swaziland", continent: "Africa" },
  { city: "Dodoma", country: "Tanzania", continent: "Africa" },
  { city: "Lomé", country: "Togo", continent: "Africa" },
  { city: "Tunis", country: "Tunisia", continent: "Africa" },
  { city: "Kampala", country: "Uganda", continent: "Africa" },
  { city: "Laayoune", country: "Western Sahara", continent: "Africa" },
];
